CREATE TABLE salesforce.report_myoffers_unfulfilled_rebate_v3__c (
    rebate__c double precision,
    merchant_name__c character varying(200),
    offer_id__c double precision,
    credit_amount__c double precision,
    offer__c character varying(18),
    transaction_type__c character varying(25),
    name character varying(80),
    rebate_transaction_id__c character varying(75),
    rebate_type__c character varying(10),
    lastmodifieddate timestamp without time zone,
    ownerid character varying(18),
    isdeleted boolean,
    systemmodstamp timestamp without time zone,
    lastmodifiedbyid character varying(18),
    merchant_id__c character varying(30),
    currency__c character varying(10),
    unfulfilled_days__c double precision,
    rebate_issue_date__c date,
    offer_name__c character varying(80),
    masked_client_account__c character varying(25),
    createddate timestamp without time zone,
    qualifying_transaction_date__c date,
    qualifying_transaction_value__c double precision,
    clientoffer_id__c double precision,
    createdbyid character varying(18),
    rebate_status_v3__c character varying(80),
    merchant__c character varying(18),
    instruction_sent_date__c date,
    sfid character varying(18),
    _hc_lastop character varying(32),
    _hc_err text,
    id serial PRIMARY KEY NOT NULL
);
