CREATE TABLE salesforce.report_myoffers_refund_v3__c (
    offer__c character varying(18),
    transaction_type__c character varying(50),
    name character varying(80),
    offerid__c double precision,
    transactionamount__c double precision,
    lastmodifieddate timestamp without time zone,
    ownerid character varying(18),
    isdeleted boolean,
    systemmodstamp timestamp without time zone,
    lastmodifiedbyid character varying(18),
    merchant_id__c character varying(100),
    transaction_date__c timestamp without time zone,
    client_account_number__c character varying(255),
    transaction_type_name__c character varying(1300),
    createddate timestamp without time zone,
    client_hash_srf__c character varying(255),
    createdbyid character varying(18),
    merchant__c character varying(18),
    sfid character varying(18),
    id serial PRIMARY KEY,
    _hc_lastop character varying(32),
    _hc_err text
);
