CREATE TABLE salesforce.product__c (
    systemmodstamp timestamp without time zone,
    sfid character varying(18),
    tlp_currency__c character varying(255),
    product_code_external__c character varying(1300),
    isdeleted boolean,
    product_type_external__c character varying(1300),
    dda_service_fee_option__c double precision,
    product_code__c character varying(30),
    _hc_err text,
    is_eligible_for_myoffers__c boolean,
    _hc_lastop character varying(32),
    id INTEGER PRIMARY KEY NOT NULL,
    createddate timestamp without time zone,
    lastmodifieddate timestamp without time zone,
    lastmodifiedbyid character varying(18),
    product_name_fr__c character varying(80),
    recordtypeid character varying(18),
    createdbyid character varying(18),
    ownerid character varying(18),
    base_points__c double precision,
    name character varying(80),
    dda_account_type_code__c double precision,
    dda_account_classification_code__c double precision
);
