CREATE TABLE salesforce.report_myoffers_rebate_journal_record_v3__c (
    merchant_name__c character varying(200),
    cc_credit_amount__c double precision,
    rebate_points__c double precision,
    offer_id__c double precision,
    offer__c character varying(50),
    rebate_dollars__c double precision,
    transaction_type__c character varying(50),
    qualifying_transaction_date__c date,
    amount__c double precision,
    name character varying(80),
    rebate_transaction_id__c character varying(75),
    rebate_type__c character varying(10),
    lastmodifieddate timestamp without time zone,
    ownerid character varying(50),
    isdeleted boolean,
    systemmodstamp timestamp without time zone,
    lastmodifiedbyid character varying(50),
    merchant_id__c character varying(30),
    fullfilled_wmresults__c double precision,
    base_points__c double precision,
    currency__c character varying(10),
    client_id__c character varying(50),
    product__c character varying(50),
    pba_credit_amount__c double precision,
    fulfilled_date__c date,
    offer_name__c character varying(80),
    masked_client_account__c character varying(50),
    createddate timestamp without time zone,
    createdbyid character varying(50),
    merchant__c character varying(50),
    instruction_sent_date__c date,
    sfid character varying(50),
    id serial PRIMARY KEY,
    _hc_lastop character varying(32),
    _hc_err text,
    total_credit_amount__c double precision,
    rebate_status_v3__c character varying(255),
    rebate_status__c character varying(255),
    qualifying_transaction_value__c double precision,
    "ucin_external_id__c" character varying(50)
);
