version: 2
jobs:
  build:
    docker:

      # See https://circleci.com/docs/2.0/language-javascript/ for more details
      - image: circleci/node:8.4.0
        environment:
          NODE_ENV: test
          SFTP_CONNECTION_URL: sftp://user:password@localhost:36168

      - image: circleci/postgres:10.2
        environment:
          POSTGRES_DB: rebate_management_test
          POSTGRES_USER: rebate_management_test

      # - image: zookeeper
      #   hostname: zookeeper
      #   ports:
      #     - 2181:2181 # Client port (used by tests)
      #     - 2888:2888 # Follower port
      #     - 3888:3888 # Election port
      #   environment:
      #     ZOO_MY_ID: 1
      #     ZOO_SERVERS: server.1=0.0.0.0:2888:3888

      # - image: wurstmeister/kafka
      #   ports:
      #     - 9092:9092
      #   environment:
      #     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    dependencies:
      cache_directories:
        - ~/.cache/yarn

    steps:
      - run: sudo apt-get update
      - run: sudo apt install libsasl2-dev rsync
      - run: sudo npm install --global yarn@^1.3.2
      - checkout
      - run: yarn install
      - run: bin/build
      - run: bin/dbmigrate up
      - run: bin/test --exit --except @kafka
      - run: bin/lint
